export type Language = "en" | "te" | "hi";

export const LANGUAGES = [
  { code: "en" as Language, label: "English", flag: "🇬🇧" },
  { code: "te" as Language, label: "తెలుగు", flag: "🇮🇳" },
  { code: "hi" as Language, label: "हिंदी", flag: "🇮🇳" },
];

export const t = {
  en: {
    appName: "KrishiHealth AI",
    tagline: "Your Smart Farming Companion",
    home: "Home",
    disease: "Disease Detect",
    health: "Health Check",
    mandi: "Mandi Prices",
    alerts: "SMS Alerts",
    chat: "AI Chat",
    dashboard: "Dashboard",
    language: "Language",
    selectLanguage: "Select Language",
    detectDisease: "Detect Crop Disease",
    uploadPhoto: "Upload Crop Photo",
    takePhoto: "Take Photo",
    orDescribe: "Or describe the crop problem",
    cropName: "Crop Name",
    analyze: "Analyze Disease",
    analyzing: "Analyzing...",
    diseaseFound: "Disease Detected",
    noDisease: "Healthy Crop",
    severity: "Severity",
    solution: "Solution",
    actionPlan: "Action Plan",
    spreadInfo: "Spread Info",
    medicine: "Recommended Medicine",
    alertNeighbors: "Alert Neighbor Farmers",
    sendSMS: "Send SMS Alert",
    phoneNumbers: "Phone Numbers (comma separated)",
    healthCheckin: "Health Check-in",
    morningSession: "Morning Check (7 AM)",
    noonSession: "Midday Check (12 PM)",
    eveningSession: "Evening Check (6 PM)",
    startCheckin: "Start Health Check",
    submit: "Submit",
    next: "Next",
    back: "Back",
    aiAdvice: "AI Health Advice",
    statusGreen: "All Good",
    statusYellow: "Caution Needed",
    statusRed: "See Doctor Immediately",
    mandiPrices: "Mandi Prices",
    refreshPrices: "Refresh Prices",
    refreshing: "Refreshing...",
    cropNameCol: "Crop",
    minPrice: "Min (₹/qtl)",
    maxPrice: "Max (₹/qtl)",
    modalPrice: "Modal (₹/qtl)",
    market: "Market",
    state: "State",
    date: "Date",
    smsAlerts: "SMS Alerts",
    sendAlert: "Send Alert",
    message: "Message",
    phone: "Phone Number",
    sending: "Sending...",
    sent: "Sent",
    failed: "Failed",
    aiChat: "AI Farming Chat",
    typeMessage: "Type your farming question...",
    voiceInput: "Voice Input",
    voiceOutput: "Voice Output",
    listening: "Listening...",
    speak: "Speak",
    recentDetections: "Recent Detections",
    recentCheckins: "Recent Health Check-ins",
    noData: "No data yet",
    mild: "Mild",
    moderate: "Moderate",
    severe: "Severe",
    hours06: "Hours 0-6",
    hours624: "Hours 6-24",
    hours2448: "Hours 24-48",
    tips: "Health Tips",
    nearestPHC: "Nearest PHC",
  },
  te: {
    appName: "కృషిహెల్త్ AI",
    tagline: "మీ తెలివైన వ్యవసాయ సహాయకుడు",
    home: "హోమ్",
    disease: "వ్యాధి గుర్తింపు",
    health: "ఆరోగ్య తనిఖీ",
    mandi: "మండి ధరలు",
    alerts: "SMS హెచ్చరికలు",
    chat: "AI చాట్",
    dashboard: "డాష్‌బోర్డ్",
    language: "భాష",
    selectLanguage: "భాష ఎంచుకోండి",
    detectDisease: "పంట వ్యాధి గుర్తించండి",
    uploadPhoto: "పంట ఫోటో అప్‌లోడ్ చేయండి",
    takePhoto: "ఫోటో తీయండి",
    orDescribe: "లేదా సమస్య వివరించండి",
    cropName: "పంట పేరు",
    analyze: "వ్యాధి విశ్లేషణ",
    analyzing: "విశ్లేషిస్తోంది...",
    diseaseFound: "వ్యాధి గుర్తించబడింది",
    noDisease: "ఆరోగ్యకరమైన పంట",
    severity: "తీవ్రత",
    solution: "పరిష్కారం",
    actionPlan: "చర్య ప్రణాళిక",
    spreadInfo: "వ్యాప్తి సమాచారం",
    medicine: "సిఫారసు చేయబడిన మందు",
    alertNeighbors: "పొరుగు రైతులకు హెచ్చరించండి",
    sendSMS: "SMS హెచ్చరిక పంపండి",
    phoneNumbers: "ఫోన్ నంబర్లు (కామాతో వేరు చేయండి)",
    healthCheckin: "ఆరోగ్య తనిఖీ",
    morningSession: "ఉదయం తనిఖీ (7 AM)",
    noonSession: "మధ్యాహ్నం తనిఖీ (12 PM)",
    eveningSession: "సాయంత్రం తనిఖీ (6 PM)",
    startCheckin: "ఆరోగ్య తనిఖీ ప్రారంభించండి",
    submit: "సమర్పించు",
    next: "తదుపరి",
    back: "వెనక్కి",
    aiAdvice: "AI ఆరోగ్య సలహా",
    statusGreen: "అన్నీ బాగున్నాయి",
    statusYellow: "కొంచెం జాగ్రత్త అవసరం",
    statusRed: "వెంటనే డాక్టర్ దగ్గరకు వెళ్ళండి",
    mandiPrices: "మండి ధరలు",
    refreshPrices: "ధరలు రిఫ్రెష్ చేయండి",
    refreshing: "రిఫ్రెష్ అవుతోంది...",
    cropNameCol: "పంట",
    minPrice: "కనిష్ట (₹/క్వింటల్)",
    maxPrice: "గరిష్ట (₹/క్వింటల్)",
    modalPrice: "మోడల్ (₹/క్వింటల్)",
    market: "మార్కెట్",
    state: "రాష్ట్రం",
    date: "తేదీ",
    smsAlerts: "SMS హెచ్చరికలు",
    sendAlert: "హెచ్చరిక పంపండి",
    message: "సందేశం",
    phone: "ఫోన్ నంబర్",
    sending: "పంపుతోంది...",
    sent: "పంపబడింది",
    failed: "విఫలమైంది",
    aiChat: "AI వ్యవసాయ చాట్",
    typeMessage: "మీ వ్యవసాయ ప్రశ్న టైప్ చేయండి...",
    voiceInput: "వాయిస్ ఇన్‌పుట్",
    voiceOutput: "వాయిస్ అవుట్‌పుట్",
    listening: "వింటోంది...",
    speak: "మాట్లాడండి",
    recentDetections: "ఇటీవలి గుర్తింపులు",
    recentCheckins: "ఇటీవలి ఆరోగ్య తనిఖీలు",
    noData: "డేటా లేదు",
    mild: "తేలికపాటి",
    moderate: "మధ్యస్థ",
    severe: "తీవ్రమైన",
    hours06: "గంటలు 0-6",
    hours624: "గంటలు 6-24",
    hours2448: "గంటలు 24-48",
    tips: "ఆరోగ్య చిట్కాలు",
    nearestPHC: "సమీప PHC",
  },
  hi: {
    appName: "कृषिहेल्थ AI",
    tagline: "आपका स्मार्ट खेती सहायक",
    home: "होम",
    disease: "रोग पहचान",
    health: "स्वास्थ्य जांच",
    mandi: "मंडी भाव",
    alerts: "SMS अलर्ट",
    chat: "AI चैट",
    dashboard: "डैशबोर्ड",
    language: "भाषा",
    selectLanguage: "भाषा चुनें",
    detectDisease: "फसल रोग पहचानें",
    uploadPhoto: "फसल की फोटो अपलोड करें",
    takePhoto: "फोटो लें",
    orDescribe: "या समस्या बताएं",
    cropName: "फसल का नाम",
    analyze: "रोग विश्लेषण",
    analyzing: "विश्लेषण हो रहा है...",
    diseaseFound: "रोग पाया गया",
    noDisease: "स्वस्थ फसल",
    severity: "गंभीरता",
    solution: "समाधान",
    actionPlan: "कार्य योजना",
    spreadInfo: "फैलाव जानकारी",
    medicine: "अनुशंसित दवाई",
    alertNeighbors: "पड़ोसी किसानों को अलर्ट करें",
    sendSMS: "SMS अलर्ट भेजें",
    phoneNumbers: "फोन नंबर (कॉमा से अलग करें)",
    healthCheckin: "स्वास्थ्य जांच",
    morningSession: "सुबह की जांच (7 बजे)",
    noonSession: "दोपहर की जांच (12 बजे)",
    eveningSession: "शाम की जांच (6 बजे)",
    startCheckin: "स्वास्थ्य जांच शुरू करें",
    submit: "जमा करें",
    next: "अगला",
    back: "वापस",
    aiAdvice: "AI स्वास्थ्य सलाह",
    statusGreen: "सब ठीक है",
    statusYellow: "थोड़ी सावधानी जरूरी है",
    statusRed: "तुरंत डॉक्टर के पास जाएं",
    mandiPrices: "मंडी भाव",
    refreshPrices: "भाव ताज़ा करें",
    refreshing: "ताज़ा हो रहा है...",
    cropNameCol: "फसल",
    minPrice: "न्यूनतम (₹/क्विंटल)",
    maxPrice: "अधिकतम (₹/क्विंटल)",
    modalPrice: "मोडल (₹/क्विंटल)",
    market: "मंडी",
    state: "राज्य",
    date: "तारीख",
    smsAlerts: "SMS अलर्ट",
    sendAlert: "अलर्ट भेजें",
    message: "संदेश",
    phone: "फोन नंबर",
    sending: "भेज रहे हैं...",
    sent: "भेजा गया",
    failed: "असफल",
    aiChat: "AI खेती चैट",
    typeMessage: "अपना खेती सवाल लिखें...",
    voiceInput: "आवाज़ इनपुट",
    voiceOutput: "आवाज़ आउटपुट",
    listening: "सुन रहे हैं...",
    speak: "बोलें",
    recentDetections: "हाल की पहचान",
    recentCheckins: "हाल की स्वास्थ्य जांचें",
    noData: "कोई डेटा नहीं",
    mild: "हल्का",
    moderate: "मध्यम",
    severe: "गंभीर",
    hours06: "घंटे 0-6",
    hours624: "घंटे 6-24",
    hours2448: "घंटे 24-48",
    tips: "स्वास्थ्य सुझाव",
    nearestPHC: "निकटतम PHC",
  },
};

export function useTranslation(lang: Language) {
  return t[lang] || t.en;
}
