export type Language =
  | "en"
  | "te"
  | "hi"
  | "bn"
  | "ta"
  | "mr"
  | "gu"
  | "kn"
  | "ml"
  | "pa"
  | "ur"
  | "or"
  | "as"
  | "ne"
  | "sd"
  | "mai"
  | "kok";

export const LANGUAGES = [
  {
    code: "en" as Language,
    label: "English",
    native: "English",
    flag: "🇬🇧",
    quality: "100%",
  },
  {
    code: "hi" as Language,
    label: "Hindi",
    native: "हिंदी",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "te" as Language,
    label: "Telugu",
    native: "తెలుగు",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "bn" as Language,
    label: "Bengali",
    native: "বাংলা",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "ta" as Language,
    label: "Tamil",
    native: "தமிழ்",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "mr" as Language,
    label: "Marathi",
    native: "मराठी",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "gu" as Language,
    label: "Gujarati",
    native: "ગુજરાતી",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "kn" as Language,
    label: "Kannada",
    native: "ಕನ್ನಡ",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "ml" as Language,
    label: "Malayalam",
    native: "മലയാളം",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "pa" as Language,
    label: "Punjabi",
    native: "ਪੰਜਾਬੀ",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "ur" as Language,
    label: "Urdu",
    native: "اردو",
    flag: "🇮🇳",
    quality: "100%",
  },
  {
    code: "or" as Language,
    label: "Odia",
    native: "ଓଡ଼ିଆ",
    flag: "🇮🇳",
    quality: "90%",
  },
  {
    code: "as" as Language,
    label: "Assamese",
    native: "অসমীয়া",
    flag: "🇮🇳",
    quality: "90%",
  },
  {
    code: "ne" as Language,
    label: "Nepali",
    native: "नेपाली",
    flag: "🇮🇳",
    quality: "90%",
  },
  {
    code: "sd" as Language,
    label: "Sindhi",
    native: "سنڌي",
    flag: "🇮🇳",
    quality: "90%",
  },
  {
    code: "mai" as Language,
    label: "Maithili",
    native: "मैथिली",
    flag: "🇮🇳",
    quality: "90%",
  },
  {
    code: "kok" as Language,
    label: "Konkani",
    native: "कोंकणी",
    flag: "🇮🇳",
    quality: "90%",
  },
];

type TX = {
  appName: string;
  tagline: string;
  home: string;
  disease: string;
  health: string;
  mandi: string;
  alerts: string;
  chat: string;
  language: string;
  selectLanguage: string;
  detectDisease: string;
  uploadPhoto: string;
  takePhoto: string;
  orDescribe: string;
  cropName: string;
  analyze: string;
  analyzing: string;
  solution: string;
  actionPlan: string;
  spreadInfo: string;
  medicine: string;
  alertNeighbors: string;
  sendSMS: string;
  phoneNumbers: string;
  healthCheckin: string;
  morningSession: string;
  noonSession: string;
  eveningSession: string;
  startCheckin: string;
  back: string;
  aiAdvice: string;
  statusGreen: string;
  statusYellow: string;
  statusRed: string;
  mandiPrices: string;
  refreshPrices: string;
  refreshing: string;
  cropNameCol: string;
  minPrice: string;
  maxPrice: string;
  modalPrice: string;
  market: string;
  state: string;
  date: string;
  smsAlerts: string;
  sendAlert: string;
  message: string;
  phone: string;
  sending: string;
  sent: string;
  failed: string;
  aiChat: string;
  typeMessage: string;
  voiceInput: string;
  listening: string;
  speak: string;
  recentDetections: string;
  recentCheckins: string;
  noData: string;
  mild: string;
  moderate: string;
  severe: string;
  tips: string;
  nearestPHC: string;
};

export const t: Record<string, TX> = {
  en: {
    appName: "KrishiHealth AI",
    tagline: "Your Smart Farming Companion",
    home: "Home",
    disease: "Disease Detect",
    health: "Health Check",
    mandi: "Mandi Prices",
    alerts: "SMS Alerts",
    chat: "AI Chat",
    language: "Language",
    selectLanguage: "Select Language",
    detectDisease: "Detect Crop Disease",
    uploadPhoto: "Upload Crop Photo",
    takePhoto: "Take Photo",
    orDescribe: "Or describe the crop problem",
    cropName: "Crop Name",
    analyze: "Analyze Disease",
    analyzing: "Analyzing...",
    solution: "Solution",
    actionPlan: "Action Plan",
    spreadInfo: "Spread Info",
    medicine: "Recommended Medicine",
    alertNeighbors: "Alert Neighbor Farmers",
    sendSMS: "Send SMS Alert",
    phoneNumbers: "Phone Numbers (comma separated)",
    healthCheckin: "Health Check-in",
    morningSession: "Morning Check (7 AM)",
    noonSession: "Midday Check (12 PM)",
    eveningSession: "Evening Check (6 PM)",
    startCheckin: "Start Health Check",
    back: "Back",
    aiAdvice: "AI Health Advice",
    statusGreen: "All Good",
    statusYellow: "Caution Needed",
    statusRed: "See Doctor Immediately",
    mandiPrices: "Mandi Prices",
    refreshPrices: "Refresh Prices",
    refreshing: "Refreshing...",
    cropNameCol: "Crop",
    minPrice: "Min (₹/qtl)",
    maxPrice: "Max (₹/qtl)",
    modalPrice: "Modal (₹/qtl)",
    market: "Market",
    state: "State",
    date: "Date",
    smsAlerts: "SMS Alerts",
    sendAlert: "Send Alert",
    message: "Message",
    phone: "Phone Number",
    sending: "Sending...",
    sent: "Sent",
    failed: "Failed",
    aiChat: "AI Farming Chat",
    typeMessage: "Type your farming question...",
    voiceInput: "Voice Input",
    listening: "Listening...",
    speak: "Speak",
    recentDetections: "Recent Detections",
    recentCheckins: "Recent Health Check-ins",
    noData: "No data yet",
    mild: "Mild",
    moderate: "Moderate",
    severe: "Severe",
    tips: "Health Tips",
    nearestPHC: "Nearest PHC",
  },
  te: {
    appName: "కృషిహెల్త్ AI",
    tagline: "మీ తెలివైన వ్యవసాయ సహాయకుడు",
    home: "హోమ్",
    disease: "వ్యాధి గుర్తింపు",
    health: "ఆరోగ్య తనిఖీ",
    mandi: "మండి ధరలు",
    alerts: "SMS హెచ్చరికలు",
    chat: "AI చాట్",
    language: "భాష",
    selectLanguage: "భాష ఎంచుకోండి",
    detectDisease: "పంట వ్యాధి గుర్తించండి",
    uploadPhoto: "పంట ఫోటో అప్‌లోడ్ చేయండి",
    takePhoto: "ఫోటో తీయండి",
    orDescribe: "లేదా సమస్య వివరించండి",
    cropName: "పంట పేరు",
    analyze: "వ్యాధి విశ్లేషణ",
    analyzing: "విశ్లేషిస్తోంది...",
    solution: "పరిష్కారం",
    actionPlan: "చర్య ప్రణాళిక",
    spreadInfo: "వ్యాప్తి సమాచారం",
    medicine: "సిఫారసు చేయబడిన మందు",
    alertNeighbors: "పొరుగు రైతులకు హెచ్చరించండి",
    sendSMS: "SMS హెచ్చరిక పంపండి",
    phoneNumbers: "ఫోన్ నంబర్లు (కామాతో వేరు చేయండి)",
    healthCheckin: "ఆరోగ్య తనిఖీ",
    morningSession: "ఉదయం తనిఖీ (7 AM)",
    noonSession: "మధ్యాహ్నం తనిఖీ (12 PM)",
    eveningSession: "సాయంత్రం తనిఖీ (6 PM)",
    startCheckin: "ఆరోగ్య తనిఖీ ప్రారంభించండి",
    back: "వెనక్కి",
    aiAdvice: "AI ఆరోగ్య సలహా",
    statusGreen: "అన్నీ బాగున్నాయి",
    statusYellow: "కొంచెం జాగ్రత్త అవసరం",
    statusRed: "వెంటనే డాక్టర్ దగ్గరకు వెళ్ళండి",
    mandiPrices: "మండి ధరలు",
    refreshPrices: "ధరలు రిఫ్రెష్ చేయండి",
    refreshing: "రిఫ్రెష్ అవుతోంది...",
    cropNameCol: "పంట",
    minPrice: "కనిష్ట (₹/క్వింటల్)",
    maxPrice: "గరిష్ట (₹/క్వింటల్)",
    modalPrice: "మోడల్ (₹/క్వింటల్)",
    market: "మార్కెట్",
    state: "రాష్ట్రం",
    date: "తేదీ",
    smsAlerts: "SMS హెచ్చరికలు",
    sendAlert: "హెచ్చరిక పంపండి",
    message: "సందేశం",
    phone: "ఫోన్ నంబర్",
    sending: "పంపుతోంది...",
    sent: "పంపబడింది",
    failed: "విఫలమైంది",
    aiChat: "AI వ్యవసాయ చాట్",
    typeMessage: "మీ వ్యవసాయ ప్రశ్న టైప్ చేయండి...",
    voiceInput: "వాయిస్ ఇన్‌పుట్",
    listening: "వింటోంది...",
    speak: "మాట్లాడండి",
    recentDetections: "ఇటీవలి గుర్తింపులు",
    recentCheckins: "ఇటీవలి ఆరోగ్య తనిఖీలు",
    noData: "డేటా లేదు",
    mild: "తేలికపాటి",
    moderate: "మధ్యస్థ",
    severe: "తీవ్రమైన",
    tips: "ఆరోగ్య చిట్కాలు",
    nearestPHC: "సమీప PHC",
  },
  hi: {
    appName: "कृषिहेल्थ AI",
    tagline: "आपका स्मार्ट खेती सहायक",
    home: "होम",
    disease: "रोग पहचान",
    health: "स्वास्थ्य जांच",
    mandi: "मंडी भाव",
    alerts: "SMS अलर्ट",
    chat: "AI चैट",
    language: "भाषा",
    selectLanguage: "भाषा चुनें",
    detectDisease: "फसल रोग पहचानें",
    uploadPhoto: "फसल की फोटो अपलोड करें",
    takePhoto: "फोटो लें",
    orDescribe: "या समस्या बताएं",
    cropName: "फसल का नाम",
    analyze: "रोग विश्लेषण",
    analyzing: "विश्लेषण हो रहा है...",
    solution: "समाधान",
    actionPlan: "कार्य योजना",
    spreadInfo: "फैलाव जानकारी",
    medicine: "अनुशंसित दवाई",
    alertNeighbors: "पड़ोसी किसानों को अलर्ट करें",
    sendSMS: "SMS अलर्ट भेजें",
    phoneNumbers: "फोन नंबर (कॉमा से अलग करें)",
    healthCheckin: "स्वास्थ्य जांच",
    morningSession: "सुबह की जांच (7 बजे)",
    noonSession: "दोपहर की जांच (12 बजे)",
    eveningSession: "शाम की जांच (6 बजे)",
    startCheckin: "स्वास्थ्य जांच शुरू करें",
    back: "वापस",
    aiAdvice: "AI स्वास्थ्य सलाह",
    statusGreen: "सब ठीक है",
    statusYellow: "थोड़ी सावधानी जरूरी है",
    statusRed: "तुरंत डॉक्टर के पास जाएं",
    mandiPrices: "मंडी भाव",
    refreshPrices: "भाव ताज़ा करें",
    refreshing: "ताज़ा हो रहा है...",
    cropNameCol: "फसल",
    minPrice: "न्यूनतम (₹/क्विंटल)",
    maxPrice: "अधिकतम (₹/क्विंटल)",
    modalPrice: "मोडल (₹/क्विंटल)",
    market: "मंडी",
    state: "राज्य",
    date: "तारीख",
    smsAlerts: "SMS अलर्ट",
    sendAlert: "अलर्ट भेजें",
    message: "संदेश",
    phone: "फोन नंबर",
    sending: "भेज रहे हैं...",
    sent: "भेजा गया",
    failed: "असफल",
    aiChat: "AI खेती चैट",
    typeMessage: "अपना खेती सवाल लिखें...",
    voiceInput: "आवाज़ इनपुट",
    listening: "सुन रहे हैं...",
    speak: "बोलें",
    recentDetections: "हाल की पहचान",
    recentCheckins: "हाल की स्वास्थ्य जांचें",
    noData: "कोई डेटा नहीं",
    mild: "हल्का",
    moderate: "मध्यम",
    severe: "गंभीर",
    tips: "स्वास्थ्य सुझाव",
    nearestPHC: "निकटतम PHC",
  },
  bn: {
    appName: "কৃষিহেলথ AI",
    tagline: "আপনার স্মার্ট কৃষি সহায়ক",
    home: "হোম",
    disease: "রোগ সনাক্ত",
    health: "স্বাস্থ্য পরীক্ষা",
    mandi: "মান্ডি মূল্য",
    alerts: "SMS সতর্কতা",
    chat: "AI চ্যাট",
    language: "ভাষা",
    selectLanguage: "ভাষা নির্বাচন করুন",
    detectDisease: "ফসলের রোগ সনাক্ত করুন",
    uploadPhoto: "ফসলের ছবি আপলোড করুন",
    takePhoto: "ছবি তুলুন",
    orDescribe: "বা সমস্যা বর্ণনা করুন",
    cropName: "ফসলের নাম",
    analyze: "রোগ বিশ্লেষণ",
    analyzing: "বিশ্লেষণ হচ্ছে...",
    solution: "সমাধান",
    actionPlan: "কর্ম পরিকল্পনা",
    spreadInfo: "বিস্তার তথ্য",
    medicine: "প্রস্তাবিত ওষুধ",
    alertNeighbors: "প্রতিবেশী কৃষকদের সতর্ক করুন",
    sendSMS: "SMS সতর্কতা পাঠান",
    phoneNumbers: "ফোন নম্বর (কমা দিয়ে আলাদা করুন)",
    healthCheckin: "স্বাস্থ্য পরীক্ষা",
    morningSession: "সকালের পরীক্ষা (৭টা)",
    noonSession: "দুপুরের পরীক্ষা (১২টা)",
    eveningSession: "সন্ধ্যার পরীক্ষা (৬টা)",
    startCheckin: "স্বাস্থ্য পরীক্ষা শুরু করুন",
    back: "পিছনে",
    aiAdvice: "AI স্বাস্থ্য পরামর্শ",
    statusGreen: "সব ঠিক আছে",
    statusYellow: "সামান্য সতর্কতা দরকার",
    statusRed: "অবিলম্বে ডাক্তার দেখান",
    mandiPrices: "মান্ডি মূল্য",
    refreshPrices: "মূল্য রিফ্রেশ করুন",
    refreshing: "রিফ্রেশ হচ্ছে...",
    cropNameCol: "ফসল",
    minPrice: "সর্বনিম্ন (₹/কুইন্টাল)",
    maxPrice: "সর্বোচ্চ (₹/কুইন্টাল)",
    modalPrice: "মোডাল (₹/কুইন্টাল)",
    market: "বাজার",
    state: "রাজ্য",
    date: "তারিখ",
    smsAlerts: "SMS সতর্কতা",
    sendAlert: "সতর্কতা পাঠান",
    message: "বার্তা",
    phone: "ফোন নম্বর",
    sending: "পাঠানো হচ্ছে...",
    sent: "পাঠানো হয়েছে",
    failed: "ব্যর্থ",
    aiChat: "AI কৃষি চ্যাট",
    typeMessage: "আপনার কৃষি প্রশ্ন লিখুন...",
    voiceInput: "ভয়েস ইনপুট",
    listening: "শুনছি...",
    speak: "বলুন",
    recentDetections: "সাম্প্রতিক সনাক্তকরণ",
    recentCheckins: "সাম্প্রতিক স্বাস্থ্য পরীক্ষা",
    noData: "কোনো ডেটা নেই",
    mild: "হালকা",
    moderate: "মাঝারি",
    severe: "গুরুতর",
    tips: "স্বাস্থ্য টিপস",
    nearestPHC: "নিকটতম PHC",
  },
  ta: {
    appName: "கிருஷிஹெல்த் AI",
    tagline: "உங்கள் ஸ்மார்ட் விவசாய உதவியாளர்",
    home: "முகப்பு",
    disease: "நோய் கண்டறிதல்",
    health: "உடல்நல சோதனை",
    mandi: "சந்தை விலை",
    alerts: "SMS எச்சரிக்கை",
    chat: "AI அரட்டை",
    language: "மொழி",
    selectLanguage: "மொழியை தேர்ந்தெடுக்கவும்",
    detectDisease: "பயிர் நோயை கண்டறியவும்",
    uploadPhoto: "பயிர் புகைப்படம் பதிவேற்றவும்",
    takePhoto: "புகைப்படம் எடுக்கவும்",
    orDescribe: "அல்லது பிரச்சனையை விவரிக்கவும்",
    cropName: "பயிர் பெயர்",
    analyze: "நோய் பகுப்பாய்வு",
    analyzing: "பகுப்பாய்வு செய்கிறது...",
    solution: "தீர்வு",
    actionPlan: "செயல் திட்டம்",
    spreadInfo: "பரவல் தகவல்",
    medicine: "பரிந்துரைக்கப்பட்ட மருந்து",
    alertNeighbors: "அண்டை விவசாயிகளை எச்சரிக்கவும்",
    sendSMS: "SMS எச்சரிக்கை அனுப்பவும்",
    phoneNumbers: "தொலைபேசி எண்கள் (கமாவால் பிரிக்கவும்)",
    healthCheckin: "உடல்நல சோதனை",
    morningSession: "காலை சோதனை (காலை 7)",
    noonSession: "நண்பகல் சோதனை (மதியம் 12)",
    eveningSession: "மாலை சோதனை (மாலை 6)",
    startCheckin: "உடல்நல சோதனை தொடங்கவும்",
    back: "பின்னால்",
    aiAdvice: "AI உடல்நல ஆலோசனை",
    statusGreen: "அனைத்தும் நலமாக உள்ளது",
    statusYellow: "கொஞ்சம் கவனம் தேவை",
    statusRed: "உடனே மருத்துவரை பாருங்கள்",
    mandiPrices: "சந்தை விலை",
    refreshPrices: "விலைகளை புதுப்பிக்கவும்",
    refreshing: "புதுப்பிக்கிறது...",
    cropNameCol: "பயிர்",
    minPrice: "குறைந்தபட்சம் (₹/குவிண்டால்)",
    maxPrice: "அதிகபட்சம் (₹/குவிண்டால்)",
    modalPrice: "மோடல் (₹/குவிண்டால்)",
    market: "சந்தை",
    state: "மாநிலம்",
    date: "தேதி",
    smsAlerts: "SMS எச்சரிக்கை",
    sendAlert: "எச்சரிக்கை அனுப்பவும்",
    message: "செய்தி",
    phone: "தொலைபேசி எண்",
    sending: "அனுப்புகிறது...",
    sent: "அனுப்பப்பட்டது",
    failed: "தோல்வி",
    aiChat: "AI விவசாய அரட்டை",
    typeMessage: "உங்கள் விவசாய கேள்வியை தட்டச்சு செய்யுங்கள்...",
    voiceInput: "குரல் உள்ளீடு",
    listening: "கேட்கிறது...",
    speak: "பேசுங்கள்",
    recentDetections: "சமீபத்திய கண்டறிதல்கள்",
    recentCheckins: "சமீபத்திய உடல்நல சோதனைகள்",
    noData: "தரவு இல்லை",
    mild: "லேசான",
    moderate: "மிதமான",
    severe: "கடுமையான",
    tips: "உடல்நல குறிப்புகள்",
    nearestPHC: "அருகிலுள்ள PHC",
  },
  mr: {
    appName: "कृषिहेल्थ AI",
    tagline: "तुमचा स्मार्ट शेती सहाय्यक",
    home: "मुख्यपृष्ठ",
    disease: "रोग ओळख",
    health: "आरोग्य तपासणी",
    mandi: "मंडी भाव",
    alerts: "SMS अलर्ट",
    chat: "AI चॅट",
    language: "भाषा",
    selectLanguage: "भाषा निवडा",
    detectDisease: "पिकाचा रोग ओळखा",
    uploadPhoto: "पिकाचा फोटो अपलोड करा",
    takePhoto: "फोटो काढा",
    orDescribe: "किंवा समस्या सांगा",
    cropName: "पिकाचे नाव",
    analyze: "रोग विश्लेषण",
    analyzing: "विश्लेषण होत आहे...",
    solution: "उपाय",
    actionPlan: "कृती योजना",
    spreadInfo: "प्रसार माहिती",
    medicine: "शिफारस केलेले औषध",
    alertNeighbors: "शेजारी शेतकऱ्यांना सावध करा",
    sendSMS: "SMS अलर्ट पाठवा",
    phoneNumbers: "फोन नंबर (स्वल्पविरामाने वेगळे करा)",
    healthCheckin: "आरोग्य तपासणी",
    morningSession: "सकाळची तपासणी (७ वाजता)",
    noonSession: "दुपारची तपासणी (१२ वाजता)",
    eveningSession: "संध्याकाळची तपासणी (६ वाजता)",
    startCheckin: "आरोग्य तपासणी सुरू करा",
    back: "मागे",
    aiAdvice: "AI आरोग्य सल्ला",
    statusGreen: "सर्व ठीक आहे",
    statusYellow: "थोडी काळजी आवश्यक",
    statusRed: "ताबडतोब डॉक्टरकडे जा",
    mandiPrices: "मंडी भाव",
    refreshPrices: "भाव रिफ्रेश करा",
    refreshing: "रिफ्रेश होत आहे...",
    cropNameCol: "पीक",
    minPrice: "किमान (₹/क्विंटल)",
    maxPrice: "कमाल (₹/क्विंटल)",
    modalPrice: "मोडल (₹/क्विंटल)",
    market: "बाजार",
    state: "राज्य",
    date: "तारीख",
    smsAlerts: "SMS अलर्ट",
    sendAlert: "अलर्ट पाठवा",
    message: "संदेश",
    phone: "फोन नंबर",
    sending: "पाठवत आहे...",
    sent: "पाठवले",
    failed: "अयशस्वी",
    aiChat: "AI शेती चॅट",
    typeMessage: "तुमचा शेती प्रश्न टाइप करा...",
    voiceInput: "व्हॉइस इनपुट",
    listening: "ऐकत आहे...",
    speak: "बोला",
    recentDetections: "अलीकडील ओळख",
    recentCheckins: "अलीकडील आरोग्य तपासण्या",
    noData: "डेटा नाही",
    mild: "सौम्य",
    moderate: "मध्यम",
    severe: "गंभीर",
    tips: "आरोग्य टिप्स",
    nearestPHC: "जवळचे PHC",
  },
  gu: {
    appName: "કૃષિહેલ્થ AI",
    tagline: "તમારો સ્માર્ટ ખેતી સહાયક",
    home: "હોમ",
    disease: "રોગ ઓળખ",
    health: "સ્વાસ્થ્ય તપાસ",
    mandi: "મંડી ભાવ",
    alerts: "SMS ચેતવણી",
    chat: "AI ચેટ",
    language: "ભાષા",
    selectLanguage: "ભાષા પસંદ કરો",
    detectDisease: "પાકનો રોગ ઓળખો",
    uploadPhoto: "પાકનો ફોટો અપલોડ કરો",
    takePhoto: "ફોટો લો",
    orDescribe: "અથવા સમસ્યા જણાવો",
    cropName: "પાકનું નામ",
    analyze: "રોગ વિશ્લેષણ",
    analyzing: "વિશ્લેષણ થઈ રહ્યું છે...",
    solution: "ઉકેલ",
    actionPlan: "કાર્ય યોજના",
    spreadInfo: "ફેલાવો માહિતી",
    medicine: "ભલામણ કરેલ દવા",
    alertNeighbors: "પડોશી ખેડૂતોને ચેતવો",
    sendSMS: "SMS ચેતવણી મોકલો",
    phoneNumbers: "ફોન નંબર (અલ્પવિરામ સાથે)",
    healthCheckin: "સ્વાસ્થ્ય તપાસ",
    morningSession: "સવારની તપાસ (7 વાગ્યે)",
    noonSession: "બપોરની તપાસ (12 વાગ્યે)",
    eveningSession: "સાંજની તપાસ (6 વાગ્યે)",
    startCheckin: "સ્વાસ્થ્ય તપાસ શરૂ કરો",
    back: "પાછળ",
    aiAdvice: "AI સ્વાસ્થ્ય સલાહ",
    statusGreen: "બધું ઠીક છે",
    statusYellow: "થોડી સાવધાની જરૂરી",
    statusRed: "તરત ડૉક્ટર પાસે જાઓ",
    mandiPrices: "મંડી ભાવ",
    refreshPrices: "ભાવ રિફ્રેશ કરો",
    refreshing: "રિફ્રેશ થઈ રહ્યું છે...",
    cropNameCol: "પાક",
    minPrice: "ન્યૂનતમ (₹/ક્વિન્ટલ)",
    maxPrice: "મહત્તમ (₹/ક્વિન્ટલ)",
    modalPrice: "મોડલ (₹/ક્વિન્ટલ)",
    market: "બજાર",
    state: "રાજ્ય",
    date: "તારીખ",
    smsAlerts: "SMS ચેતવણી",
    sendAlert: "ચેતવણી મોકલો",
    message: "સંદેશ",
    phone: "ફોન નંબર",
    sending: "મોકલાઈ રહ્યું છે...",
    sent: "મોકલ્યું",
    failed: "નિષ્ફળ",
    aiChat: "AI ખેતી ચેટ",
    typeMessage: "તમારો ખેતી પ્રશ્ન ટાઇપ કરો...",
    voiceInput: "વૉઇસ ઇનપુટ",
    listening: "સાંભળી રહ્યા છીએ...",
    speak: "બોલો",
    recentDetections: "તાજેતરની ઓળખ",
    recentCheckins: "તાજેતરની સ્વાસ્થ્ય તપાસ",
    noData: "કોઈ ડેટા નથી",
    mild: "હળવો",
    moderate: "મધ્યમ",
    severe: "ગંભીર",
    tips: "સ્વાસ્થ્ય ટિપ્સ",
    nearestPHC: "નજીકનું PHC",
  },
  kn: {
    appName: "ಕೃಷಿಹೆಲ್ತ್ AI",
    tagline: "ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಸಹಾಯಕ",
    home: "ಮನೆ",
    disease: "ರೋಗ ಪತ್ತೆ",
    health: "ಆರೋಗ್ಯ ತಪಾಸಣೆ",
    mandi: "ಮಂಡಿ ಬೆಲೆ",
    alerts: "SMS ಎಚ್ಚರಿಕೆ",
    chat: "AI ಚಾಟ್",
    language: "ಭಾಷೆ",
    selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ",
    detectDisease: "ಬೆಳೆ ರೋಗ ಪತ್ತೆ ಮಾಡಿ",
    uploadPhoto: "ಬೆಳೆ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    orDescribe: "ಅಥವಾ ಸಮಸ್ಯೆ ವಿವರಿಸಿ",
    cropName: "ಬೆಳೆ ಹೆಸರು",
    analyze: "ರೋಗ ವಿಶ್ಲೇಷಣೆ",
    analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    solution: "ಪರಿಹಾರ",
    actionPlan: "ಕ್ರಿಯಾ ಯೋಜನೆ",
    spreadInfo: "ಹರಡುವಿಕೆ ಮಾಹಿತಿ",
    medicine: "ಶಿಫಾರಸು ಮಾಡಿದ ಔಷಧ",
    alertNeighbors: "ನೆರೆಯ ರೈತರನ್ನು ಎಚ್ಚರಿಸಿ",
    sendSMS: "SMS ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ",
    phoneNumbers: "ಫೋನ್ ಸಂಖ್ಯೆಗಳು (ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರ್ಪಡಿಸಿ)",
    healthCheckin: "ಆರೋಗ್ಯ ತಪಾಸಣೆ",
    morningSession: "ಬೆಳಿಗ್ಗೆ ತಪಾಸಣೆ (7 ಗಂಟೆ)",
    noonSession: "ಮಧ್ಯಾಹ್ನ ತಪಾಸಣೆ (12 ಗಂಟೆ)",
    eveningSession: "ಸಂಜೆ ತಪಾಸಣೆ (6 ಗಂಟೆ)",
    startCheckin: "ಆರೋಗ್ಯ ತಪಾಸಣೆ ಪ್ರಾರಂಭಿಸಿ",
    back: "ಹಿಂದೆ",
    aiAdvice: "AI ಆರೋಗ್ಯ ಸಲಹೆ",
    statusGreen: "ಎಲ್ಲವೂ ಚೆನ್ನಾಗಿದೆ",
    statusYellow: "ಸ್ವಲ್ಪ ಎಚ್ಚರಿಕೆ ಅಗತ್ಯ",
    statusRed: "ತಕ್ಷಣ ವೈದ್ಯರನ್ನು ನೋಡಿ",
    mandiPrices: "ಮಂಡಿ ಬೆಲೆ",
    refreshPrices: "ಬೆಲೆ ರಿಫ್ರೆಶ್ ಮಾಡಿ",
    refreshing: "ರಿಫ್ರೆಶ್ ಆಗುತ್ತಿದೆ...",
    cropNameCol: "ಬೆಳೆ",
    minPrice: "ಕನಿಷ್ಠ (₹/ಕ್ವಿಂಟಲ್)",
    maxPrice: "ಗರಿಷ್ಠ (₹/ಕ್ವಿಂಟಲ್)",
    modalPrice: "ಮೋಡಲ್ (₹/ಕ್ವಿಂಟಲ್)",
    market: "ಮಾರುಕಟ್ಟೆ",
    state: "ರಾಜ್ಯ",
    date: "ದಿನಾಂಕ",
    smsAlerts: "SMS ಎಚ್ಚರಿಕೆ",
    sendAlert: "ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ",
    message: "ಸಂದೇಶ",
    phone: "ಫೋನ್ ಸಂಖ್ಯೆ",
    sending: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    sent: "ಕಳುಹಿಸಲಾಗಿದೆ",
    failed: "ವಿಫಲ",
    aiChat: "AI ಕೃಷಿ ಚಾಟ್",
    typeMessage: "ನಿಮ್ಮ ಕೃಷಿ ಪ್ರಶ್ನೆ ಟೈಪ್ ಮಾಡಿ...",
    voiceInput: "ಧ್ವನಿ ಇನ್ಪುಟ್",
    listening: "ಆಲಿಸುತ್ತಿದ್ದೇವೆ...",
    speak: "ಮಾತನಾಡಿ",
    recentDetections: "ಇತ್ತೀಚಿನ ಪತ್ತೆಗಳು",
    recentCheckins: "ಇತ್ತೀಚಿನ ಆರೋಗ್ಯ ತಪಾಸಣೆಗಳು",
    noData: "ಡೇಟಾ ಇಲ್ಲ",
    mild: "ಸೌಮ್ಯ",
    moderate: "ಮಧ್ಯಮ",
    severe: "ತೀವ್ರ",
    tips: "ಆರೋಗ್ಯ ಸಲಹೆಗಳು",
    nearestPHC: "ಹತ್ತಿರದ PHC",
  },
  ml: {
    appName: "കൃഷിഹെൽത്ത് AI",
    tagline: "നിങ്ങളുടെ സ്മാർട്ട് കൃഷി സഹായി",
    home: "ഹോം",
    disease: "രോഗ നിർണ്ണയം",
    health: "ആരോഗ്യ പരിശോധന",
    mandi: "മണ്ടി വില",
    alerts: "SMS അലർട്ട്",
    chat: "AI ചാറ്റ്",
    language: "ഭാഷ",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    detectDisease: "വിള രോഗം കണ്ടെത്തുക",
    uploadPhoto: "വിളയുടെ ഫോട്ടോ അപ്ലോഡ് ചെയ്യുക",
    takePhoto: "ഫോട്ടോ എടുക്കുക",
    orDescribe: "അല്ലെങ്കിൽ പ്രശ്നം വിവരിക്കുക",
    cropName: "വിളയുടെ പേര്",
    analyze: "രോഗ വിശകലനം",
    analyzing: "വിശകലനം ചെയ്യുന്നു...",
    solution: "പരിഹാരം",
    actionPlan: "പ്രവർത്തന പദ്ധതി",
    spreadInfo: "വ്യാപന വിവരം",
    medicine: "ശുപാർശ ചെയ്ത മരുന്ന്",
    alertNeighbors: "അയൽ കർഷകരെ അറിയിക്കുക",
    sendSMS: "SMS അലർട്ട് അയയ്ക്കുക",
    phoneNumbers: "ഫോൺ നമ്പറുകൾ (കോമ കൊണ്ട് വേർതിരിക്കുക)",
    healthCheckin: "ആരോഗ്യ പരിശോധന",
    morningSession: "രാവിലെ പരിശോധന (7 മണി)",
    noonSession: "ഉച്ചതിരിഞ്ഞ് പരിശോധന (12 മണി)",
    eveningSession: "വൈകുന്നേരം പരിശോധന (6 മണി)",
    startCheckin: "ആരോഗ്യ പരിശോധന ആരംഭിക്കുക",
    back: "തിരിച്ച്",
    aiAdvice: "AI ആരോഗ്യ ഉപദേശം",
    statusGreen: "എല്ലാം ശരിയാണ്",
    statusYellow: "കുറച്ച് ശ്രദ്ധ ആവശ്യം",
    statusRed: "ഉടൻ ഡോക്ടറെ കാണുക",
    mandiPrices: "മണ്ടി വില",
    refreshPrices: "വില പുതുക്കുക",
    refreshing: "പുതുക്കുന്നു...",
    cropNameCol: "വിള",
    minPrice: "കുറഞ്ഞ (₹/ക്വിന്റൽ)",
    maxPrice: "കൂടിയ (₹/ക്വിന്റൽ)",
    modalPrice: "മോഡൽ (₹/ക്വിന്റൽ)",
    market: "മാർക്കറ്റ്",
    state: "സംസ്ഥാനം",
    date: "തീയതി",
    smsAlerts: "SMS അലർട്ട്",
    sendAlert: "അലർട്ട് അയയ്ക്കുക",
    message: "സന്ദേശം",
    phone: "ഫോൺ നമ്പർ",
    sending: "അയയ്ക്കുന്നു...",
    sent: "അയച്ചു",
    failed: "പരാജയപ്പെട്ടു",
    aiChat: "AI കൃഷി ചാറ്റ്",
    typeMessage: "നിങ്ങളുടെ കൃഷി ചോദ്യം ടൈപ്പ് ചെയ്യുക...",
    voiceInput: "ശബ്ദ ഇൻപുട്ട്",
    listening: "ശ്രദ്ധിക്കുന്നു...",
    speak: "സംസാരിക്കുക",
    recentDetections: "സമീപകാല കണ്ടെത്തലുകൾ",
    recentCheckins: "സമീപകാല ആരോഗ്യ പരിശോധനകൾ",
    noData: "ഡേറ്റ ഇല്ല",
    mild: "ലഘു",
    moderate: "മിതമായ",
    severe: "ഗുരുതരം",
    tips: "ആരോഗ്യ ടിപ്സ്",
    nearestPHC: "അടുത്തുള്ള PHC",
  },
  pa: {
    appName: "ਕ੍ਰਿਸ਼ੀਹੈਲਥ AI",
    tagline: "ਤੁਹਾਡਾ ਸਮਾਰਟ ਖੇਤੀ ਸਹਾਇਕ",
    home: "ਹੋਮ",
    disease: "ਰੋਗ ਪਛਾਣ",
    health: "ਸਿਹਤ ਜਾਂਚ",
    mandi: "ਮੰਡੀ ਭਾਅ",
    alerts: "SMS ਚੇਤਾਵਨੀ",
    chat: "AI ਚੈਟ",
    language: "ਭਾਸ਼ਾ",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    detectDisease: "ਫਸਲ ਦੀ ਬਿਮਾਰੀ ਪਛਾਣੋ",
    uploadPhoto: "ਫਸਲ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    takePhoto: "ਫੋਟੋ ਲਓ",
    orDescribe: "ਜਾਂ ਸਮੱਸਿਆ ਦੱਸੋ",
    cropName: "ਫਸਲ ਦਾ ਨਾਮ",
    analyze: "ਰੋਗ ਵਿਸ਼ਲੇਸ਼ਣ",
    analyzing: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    solution: "ਹੱਲ",
    actionPlan: "ਕਾਰਜ ਯੋਜਨਾ",
    spreadInfo: "ਫੈਲਾਅ ਜਾਣਕਾਰੀ",
    medicine: "ਸਿਫਾਰਸ਼ ਕੀਤੀ ਦਵਾਈ",
    alertNeighbors: "ਗੁਆਂਢੀ ਕਿਸਾਨਾਂ ਨੂੰ ਸੁਚੇਤ ਕਰੋ",
    sendSMS: "SMS ਚੇਤਾਵਨੀ ਭੇਜੋ",
    phoneNumbers: "ਫੋਨ ਨੰਬਰ (ਕੌਮੇ ਨਾਲ ਵੱਖ ਕਰੋ)",
    healthCheckin: "ਸਿਹਤ ਜਾਂਚ",
    morningSession: "ਸਵੇਰੇ ਜਾਂਚ (7 ਵਜੇ)",
    noonSession: "ਦੁਪਹਿਰੇ ਜਾਂਚ (12 ਵਜੇ)",
    eveningSession: "ਸ਼ਾਮ ਜਾਂਚ (6 ਵਜੇ)",
    startCheckin: "ਸਿਹਤ ਜਾਂਚ ਸ਼ੁਰੂ ਕਰੋ",
    back: "ਵਾਪਸ",
    aiAdvice: "AI ਸਿਹਤ ਸਲਾਹ",
    statusGreen: "ਸਭ ਠੀਕ ਹੈ",
    statusYellow: "ਥੋੜੀ ਸਾਵਧਾਨੀ ਜ਼ਰੂਰੀ",
    statusRed: "ਤੁਰੰਤ ਡਾਕਟਰ ਕੋਲ ਜਾਓ",
    mandiPrices: "ਮੰਡੀ ਭਾਅ",
    refreshPrices: "ਭਾਅ ਤਾਜ਼ਾ ਕਰੋ",
    refreshing: "ਤਾਜ਼ਾ ਹੋ ਰਿਹਾ ਹੈ...",
    cropNameCol: "ਫਸਲ",
    minPrice: "ਘੱਟੋ-ਘੱਟ (₹/ਕੁਇੰਟਲ)",
    maxPrice: "ਵੱਧ ਤੋਂ ਵੱਧ (₹/ਕੁਇੰਟਲ)",
    modalPrice: "ਮੋਡਲ (₹/ਕੁਇੰਟਲ)",
    market: "ਬਾਜ਼ਾਰ",
    state: "ਰਾਜ",
    date: "ਤਾਰੀਖ",
    smsAlerts: "SMS ਚੇਤਾਵਨੀ",
    sendAlert: "ਚੇਤਾਵਨੀ ਭੇਜੋ",
    message: "ਸੁਨੇਹਾ",
    phone: "ਫੋਨ ਨੰਬਰ",
    sending: "ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    sent: "ਭੇਜਿਆ ਗਿਆ",
    failed: "ਅਸਫਲ",
    aiChat: "AI ਖੇਤੀ ਚੈਟ",
    typeMessage: "ਆਪਣਾ ਖੇਤੀ ਸਵਾਲ ਟਾਈਪ ਕਰੋ...",
    voiceInput: "ਆਵਾਜ਼ ਇਨਪੁੱਟ",
    listening: "ਸੁਣ ਰਹੇ ਹਾਂ...",
    speak: "ਬੋਲੋ",
    recentDetections: "ਹਾਲੀਆ ਖੋਜਾਂ",
    recentCheckins: "ਹਾਲੀਆ ਸਿਹਤ ਜਾਂਚਾਂ",
    noData: "ਕੋਈ ਡੇਟਾ ਨਹੀਂ",
    mild: "ਹਲਕਾ",
    moderate: "ਮੱਧਮ",
    severe: "ਗੰਭੀਰ",
    tips: "ਸਿਹਤ ਸੁਝਾਅ",
    nearestPHC: "ਨਜ਼ਦੀਕੀ PHC",
  },
  ur: {
    appName: "کرشی ہیلتھ AI",
    tagline: "آپ کا سمارٹ کھیتی مددگار",
    home: "ہوم",
    disease: "بیماری کی پہچان",
    health: "صحت کی جانچ",
    mandi: "منڈی بھاؤ",
    alerts: "SMS الرٹ",
    chat: "AI چیٹ",
    language: "زبان",
    selectLanguage: "زبان منتخب کریں",
    detectDisease: "فصل کی بیماری پہچانیں",
    uploadPhoto: "فصل کی تصویر اپلوڈ کریں",
    takePhoto: "تصویر لیں",
    orDescribe: "یا مسئلہ بیان کریں",
    cropName: "فصل کا نام",
    analyze: "بیماری کا تجزیہ",
    analyzing: "تجزیہ ہو رہا ہے...",
    solution: "حل",
    actionPlan: "عمل کا منصوبہ",
    spreadInfo: "پھیلاؤ کی معلومات",
    medicine: "تجویز کردہ دوا",
    alertNeighbors: "پڑوسی کسانوں کو خبردار کریں",
    sendSMS: "SMS الرٹ بھیجیں",
    phoneNumbers: "فون نمبر (کوما سے الگ کریں)",
    healthCheckin: "صحت کی جانچ",
    morningSession: "صبح کی جانچ (7 بجے)",
    noonSession: "دوپہر کی جانچ (12 بجے)",
    eveningSession: "شام کی جانچ (6 بجے)",
    startCheckin: "صحت کی جانچ شروع کریں",
    back: "واپس",
    aiAdvice: "AI صحت کا مشورہ",
    statusGreen: "سب ٹھیک ہے",
    statusYellow: "تھوڑی احتیاط ضروری",
    statusRed: "فوری ڈاکٹر کے پاس جائیں",
    mandiPrices: "منڈی بھاؤ",
    refreshPrices: "بھاؤ تازہ کریں",
    refreshing: "تازہ ہو رہا ہے...",
    cropNameCol: "فصل",
    minPrice: "کم از کم (₹/کوئنٹل)",
    maxPrice: "زیادہ سے زیادہ (₹/کوئنٹل)",
    modalPrice: "ماڈل (₹/کوئنٹل)",
    market: "بازار",
    state: "ریاست",
    date: "تاریخ",
    smsAlerts: "SMS الرٹ",
    sendAlert: "الرٹ بھیجیں",
    message: "پیغام",
    phone: "فون نمبر",
    sending: "بھیجا جا رہا ہے...",
    sent: "بھیجا گیا",
    failed: "ناکام",
    aiChat: "AI کھیتی چیٹ",
    typeMessage: "اپنا کھیتی سوال ٹائپ کریں...",
    voiceInput: "آواز ان پٹ",
    listening: "سن رہے ہیں...",
    speak: "بولیں",
    recentDetections: "حالیہ پہچان",
    recentCheckins: "حالیہ صحت جانچ",
    noData: "کوئی ڈیٹا نہیں",
    mild: "ہلکا",
    moderate: "درمیانہ",
    severe: "سنگین",
    tips: "صحت کے مشورے",
    nearestPHC: "قریبی PHC",
  },
  // 90% group — UI English, AI responses perfect in these languages
  or: {} as TX,
  as: {} as TX,
  ne: {} as TX,
  sd: {} as TX,
  mai: {} as TX,
  kok: {} as TX,
};

export function useTranslation(lang: Language): TX {
  const fullUI = [
    "en",
    "te",
    "hi",
    "bn",
    "ta",
    "mr",
    "gu",
    "kn",
    "ml",
    "pa",
    "ur",
  ];
  if (fullUI.includes(lang)) return t[lang] as TX;
  return t.en;
}
